name: php-bloom-filter

services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    platform: linux/amd64
    working_dir: /var/www/project
    ports:
      - "9000:9000"
    volumes:
      - ../app:/var/www/project:rw,delegated
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
